### ISSUE TITLE
[BUG]: urllib.error.HTTPError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by Advik-B** [Owen-Cochell/cursepy#12]
logs:
```py
[19:07:31]-[INFO]: Checking widgets
[19:07:31]-[DEBUG]: <PyQt5.QtWidgets.QLabel object at 0x000002210044DDC0>
[19:07:31]-[DEBUG]: <PyQt5.QtWidgets.QLineEdit object at 0x000002210044DEE0>
[19:07:31]-[DEBUG]: <PyQt5.QtWidgets.QLineEdit object at 0x00000221005E01F0>
[19:07:31]-[DEBUG]: <PyQt5.QtWidgets.QCheckBox object at 0x00000221005E00D0>
[19:07:31]-[DEBUG]: <PyQt5.QtWidgets.QCheckBox object at 0x00000221005E0160>
[19:07:31]-[DEBUG]: <PyQt5.QtWidgets.QProgressBar object at 0x00000221005E04C0>
[19:07:31]-[DEBUG]: <PyQt5.QtWidgets.QProgressBar object at 0x00000221005E03A0>
[19:07:31]-[DEBUG]: <PyQt5.QtWidgets.QListWidget object at 0x00000221005E0790>
[19:07:31]-[DEBUG]: <PyQt5.QtWidgets.QTextEdit object at 0x00000221005E08B0>
[19:07:31]-[DEBUG]: <PyQt5.QtWidgets.QPushButton object at 0x00000221005E0940>
[19:07:31]-[DEBUG]: <PyQt5.QtWidgets.QPushButton object at 0x00000221005E09D0>
[19:07:31]-[DEBUG]: <PyQt5.QtWidgets.QPushButton object at 0x000002210044DF70>
[19:07:31]-[DEBUG]: <PyQt5.QtWidgets.QPushButton object at 0x00000221005E0280>
[19:07:31]-[INFO]: Window sucessfully loaded
[19:07:35]-[INFO]: Modpack path set to: C:/Users/advik/Downloads/sample.manifest.json
[19:07:39]-[INFO]: Output directory set to: C:/Users/advik/Downloads
[19:07:40]-[INFO]: Starting payload
[19:07:40]-[INFO]: Initializing Curse client...
[19:07:40]-[INFO]: Successfully initialized Curse client in 0.0001543999999995549 seconds
[19:07:40]-[INFO]: Initializing ModPack...
[19:07:40]-[INFO]: Manifest path set to C:/Users/advik/Downloads/sample.manifest.json
[19:07:40]-[INFO]: Loading manifest...
[19:07:40]-[INFO]: Minecraft version: 1.16.5
[19:07:40]-[INFO]: Modpack version: 1.5
[19:07:40]-[INFO]: Modpack name: Origin server modpack
[19:07:40]-[INFO]: Modpack author(s):
[19:07:40]-[INFO]: Modpack description: None
[19:07:40]-[INFO]: Modpack website: None
[19:07:40]-[INFO]: Modpack modloader: forge-36.2.0
[19:07:40]-[INFO]: Modpack config/overrides: overrides
[19:07:40]-[INFO]: Successfully loaded manifest
[19:07:40]-[INFO]: Successfully initialized ModPack in 0.020160999999999873 seconds
[19:07:40]-[INFO]: Installing ModPack...
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QTextDocument(0x2217fca6460), parent's thread is QThread(0x2217dc5a160), current thread is QThread(0x221023cce10)
QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)
[19:07:40]-[INFO]: Downloading mods to C:/Users/advik/Downloads
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QTextDocument(0x2217fca6460), parent's thread is QThread(0x2217dc5a160), current thread is QThread(0x221023cce10)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Programs\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Programs\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "s:\Github\CMPDL\src\backend.py", line 136, in install
    mod = self.c.addon(mod_["projectID"])
  File "S:\Github\CMPDL\src\venv\lib\site-packages\cursepy\wrapper.py", line 124, in addon
    return self.handle(5, addon_id)
  File "S:\Github\CMPDL\src\venv\lib\site-packages\cursepy\handlers\base.py", line 990, in handle
    inst = hand.handle(*args, **kwargs)
  File "S:\Github\CMPDL\src\venv\lib\site-packages\cursepy\handlers\base.py", line 411, in handle
    return super().handle()
  File "S:\Github\CMPDL\src\venv\lib\site-packages\cursepy\handlers\base.py", line 182, in handle
    data_bytes = self.proto_call(*args, **kwargs)
  File "S:\Github\CMPDL\src\venv\lib\site-packages\cursepy\handlers\base.py", line 376, in proto_call
    return self.proto.get_data(self.url)
  File "S:\Github\CMPDL\src\venv\lib\site-packages\cursepy\proto.py", line 220, in get_data
    req = self.low_get(url, timeout=timeout)
  File "S:\Github\CMPDL\src\venv\lib\site-packages\cursepy\proto.py", line 256, in low_get
    self.last = urlopen(req, timeout=self.timeout if None else timeout)
  File "C:\Programs\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Programs\Python39\lib\urllib\request.py", line 523, in open
    response = meth(req, response)
  File "C:\Programs\Python39\lib\urllib\request.py", line 632, in http_response
    response = self.parent.error(
  File "C:\Programs\Python39\lib\urllib\request.py", line 561, in error
    return self._call_chain(*args)
  File "C:\Programs\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Programs\Python39\lib\urllib\request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by Advik-B** [comment]
Ignore the `Qobject` logs

**Comment by OwenCochell** [comment]
Hello! Thanks for reporting this.

What operation was your program attempting to do? Also, were you using the official CurseForge handlers with a valid API key? If you key is invalid then the API will respond in this way. Also, if you are using the old ForgeSVC handlers you will also get this response as that endpoint has shut down. I'll look into testing this myself, but knowing your extra details would help us figure this out.

Thanks!

**Comment by Advik-B** [comment]
My program was trying to download a mod, yes the API key is valid
